### ISSUE TITLE
coredns too old

### ISSUE THREAD

**Issue by ablozhou** [anjia0532/gcr.io_mirror#1020]
coredns version is 4 years ago
maybe you could update to docker hub

**Comment by anjia0532** [comment]
![image](https://user-images.githubusercontent.com/15098916/180905408-6a77a882-33ec-4183-98f3-a02631a9fbaf.png)

**Comment by anjia0532** [comment]
![image](https://user-images.githubusercontent.com/15098916/180905578-1cda36c4-b590-41e2-982e-152a538217b9.png)
