### ISSUE TITLE
image anjia0532/kube-proxy-amd64:v1.10.4 not found

### ISSUE THREAD

**Issue by HanYL-coder** [anjia0532/gcr.io_mirror#12]
While I'm pulling this image, there's an error occurs.

"Error response from daemon: manifest for anjia0532/kube-proxy-amd64:v1.10.4 not found"

plz check if it is avaliable.

btw, it's very useful when blocked by gfw.

thx for what u r doing, thank u very much.

**Comment by anjia0532** [comment]
try `docker pull anjia0532/google-containers.kube-proxy-amd64:v1.10.4`

**Comment by anjia0532** [comment]
`anjia0532/image:tag` mean is `gcr.io/google-containers/image:tag` it was deprecated.

u will change to

`anjia0532/gcr.io_namespace.image:tag` mean is `gcr.io/namespace/image:tag`

support 6 namespace
```
gcr.io/google-samples/*
gcr.io/kubernetes-helm/*
gcr.io/k8s-minikube/*
gcr.io/tf-on-k8s-dogfood/*
gcr.io/spinnaker-marketplace/*
gcr.io/google-containers/*
```
