### ISSUE TITLE
添加运行conduit的镜像库

### ISSUE THREAD

**Issue by leeyr338** [anjia0532/gcr.io_mirror#13]
可以添加conduit的镜像库吗？
gcr.io/runconduit/controller:v0.4.4
gcr.io/runconduit/proxy:v0.4.4
gcr.io/runconduit/proxy-init:v0.4.4
gcr.io/runconduit/web:v0.4.4
gcr.io/runconduit/grafana:v0.4.4

**Comment by anjia0532** [comment]
已经添加到同步列表里了，不过鉴于这个 命名空间的镜像较多（4391个需要同步的），你可能得等等。
https://github.com/anjia0532/gcr.io_mirror/tree/master/runconduit ，可以通过查看这个文件夹下的文件.
比如 https://github.com/anjia0532/gcr.io_mirror/blob/master/runconduit/controller/v0.4.4.tag是否存在，来看是否已经同步完成。
*.tag是已经同步完的
*.tmp是未同步的

**Comment by anjia0532** [comment]
@leeyr338 gcr.io/runconduit/* 共计4391个镜像都同步完了

**Comment by leeyr338** [comment]
已经可以使用，谢谢！发自我的iPhone------------------ 原始邮件 ------------------发件人: AnJia  <notifications@github.com>发送时间: 2018年7月6日 09:18收件人: anjia0532/gcr.io_mirror <gcr.io_mirror@noreply.github.com>抄送: Yaorong <leeyr338@gmail.com>, Mention <mention@noreply.github.com>主题: 回复：[anjia0532/gcr.io_mirror] 添加运行conduit的镜像库 (#13)@leeyr338 gcr.io/runconduit/* 共计4391个镜像都同步完了

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/anjia0532/gcr.io_mirror","title":"anjia0532/gcr.io_mirror","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/anjia0532/gcr.io_mirror"}},"updates":{"snippets":[{"icon":"PERSON","message":"@anjia0532 in #13: @leeyr338 gcr.io/runconduit/* 共计4391个镜像都同步完了"}],"action":{"name":"View Issue","url":"https://github.com/anjia0532/gcr.io_mirror/issues/13#issuecomment-402896683"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/anjia0532/gcr.io_mirror/issues/13#issuecomment-402896683",
"url": "https://github.com/anjia0532/gcr.io_mirror/issues/13#issuecomment-402896683",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [anjia0532/gcr.io_mirror] 添加运行conduit的镜像库 (#13)",
"sections": [
{
"text": "",
"activityTitle": "**AnJia**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@anjia0532",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"anjia0532/gcr.io_mirror\",\n\"issueId\": 13,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/anjia0532/gcr.io_mirror/issues/13#issuecomment-402896683"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 353155486\n}"
}
],
"themeColor": "26292E"
}
]
