### ISSUE TITLE
https://gcr.io/v2/ and https://k8s.gcr.io/v2/

### ISSUE THREAD

**Issue by wscall** [anjia0532/gcr.io_mirror#14]
i need some resource as below,do uo have them?
https://gcr.io/v2/
https://k8s.gcr.io/v2/

**Comment by anjia0532** [comment]
? I don't understand, please explain in detail

**Comment by anjia0532** [comment]
k8s.gcr.io/{image}/{tag}
is eq
gcr.io/google-containers/{image}/{tag}
is eq
anjia0532/google-containers.{image}/{tag}
