### ISSUE TITLE
kube-cross image can not be pulled

### ISSUE THREAD

**Issue by silenceshell** [anjia0532/gcr.io_mirror#15]
hi, I want to pull the kube-cross image from your repos, but failed. I do find the image in your docker hub page.

$ docker pull anjia0532/google-containers.kube-cross:v1.10.3-1
Error response from daemon: manifest for anjia0532/google-containers.kube-cross:v1.10.3-1 not found

Is there something I missed? I build the image by myself and could pull it. This is the image `docker pull silenceshell/kube-cross:v1.10.3-1` in case you need it.

**Comment by anjia0532** [comment]
```bash
$ docker pull anjia0532/google-containers.kube-cross:V1.10.3-1
0bd44ff9c2cf: Pull complete 
047670ddbd2a: Pull complete 
ea7d5dc89438: Pull complete 
ae7ad5906a75: Pull complete 
15f6351ddb37: Pull complete 
823ef4e8c9c9: Pull complete 
dca1089cfb86: Pull complete 
29b9b71a9472: Downloading [>                                                  ]  1.593MB/168.8MB
37a3740eec54: Download complete 
614813df279a: Downloading [=>                                                 ]  1.368MB/45.42MB
19600e05fc0f: Downloading [==>                                                ]  9.535MB/183.7MB
81bc741281dc: Waiting 
c71387b8c428: Waiting 
b78b37f0eca5: Waiting
```
it's ok

exec `cat /etc/docker/daemon.json` && paste output

**Comment by silenceshell** [comment]
OH...
The problem is the tag. It should be `v1.10.3-1` not `V1.10.3-1`, lower case v.
The file `V1.10.3-1.tag` should be renamed to `v1.10.3-1.tag`.

**Comment by anjia0532** [comment]
![snipaste20180725_001607](https://user-images.githubusercontent.com/15098916/43152023-faf0c364-8f9f-11e8-9048-01ee5399c22c.png)
this image has 2 tags(V1.10.3-1 and v1.10.3-1), but i only pull && retag && push the first tag.
