### ISSUE TITLE
是否可以添加个namespace

### ISSUE THREAD

**Issue by HanYL-coder** [anjia0532/gcr.io_mirror#17]
前阵google开源了jib, 作为打包image的工具.
关联的基础镜像为gcr.io/distroless/java:latest 
是否可以麻烦添加个distroless的镜像
多谢~

**Comment by anjia0532** [comment]
可以，这就加上，你稍后再回来看看就行了

**Comment by HanYL-coder** [comment]
好的, 多谢多谢~

**Comment by anjia0532** [comment]
@HanYL-coder  好了 https://github.com/anjia0532/gcr.io_mirror/tree/master/distroless/java
