### ISSUE TITLE
[PORTER] gcr.io/k8s-staging-gateway-api/admission-server:v0.5.1

### ISSUE THREAD

**Issue by yangchuangchuang** [anjia0532/gcr.io_mirror#1704]
**为了防止被滥用，目前仅仅支持一次同步一个镜像**

**Issues 必须带 `porter` label，** 简单来说就是通过模板创建就没问题，别抖机灵自己瞎弄。

**标题必须为 `[PORTER]镜像名:tag` 的格式，** 例如`[PORTER]k8s.gcr.io/federation-controller-manager-arm64:v1.3.1-beta.1`,`[PORTER]gcr.io/google-containers/federation-controller-manager-arm64:v1.3.1-beta.1`

issues的内容无所谓，可以为空

可以参考 [已搬运镜像集锦](https://github.com/anjia0532/gcr.io_mirror/issues?q=is%3Aissue+label%3Aporter+)

**注意:**

**>>>>>>>>本项目目前仅支持 gcr.io、k8s.gcr.io、registry.k8s.io、quay.io、ghcr.io 镜像<<<<<<<<**

**Comment by jpDeng111** [comment]
请问为什么我会报错：$ docker pull anjia0532/k8s-staging-gateway-api.admission-server:v0.5.1
v0.5.1: Pulling from anjia0532/k8s-staging-gateway-api.admission-server
1cd0595314a5: Pulling fs layer 
5a256714570f: Pulling fs layer 
error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/93/93cc81c54f7d6a798c3e742b3108533c02375d03479ac864f366efd8f7164aef/data?verify=1724126623-sqp3Nko%2Fdo%2BYzQxb8emT31BvQUk%3D: dial tcp [2a03:2880:f11c:8083:face:b00c:0:25de]:443: i/o timeout

**Comment by jpDeng111** [comment]
尝试了别的版本的，也还是相同的错误
