### ISSUE TITLE
Hello, miss gcr.io/spinnaker-marketplace/halyard:stable

### ISSUE THREAD

**Issue by lotreal** [anjia0532/gcr.io_mirror#2]

**Comment by anjia0532** [comment]
this repo is only for `gcr.io/google-containers` namespace.

**Comment by anjia0532** [comment]
@lotreal it's done. ref https://github.com/anjia0532/gcr.io_mirror#total-of-17s-gcriospinnaker-marketplace-images

**Comment by lotreal** [comment]
@anjia0532 super super thanks!
