### ISSUE TITLE
gcr.io/cloud-datalab is not included?

### ISSUE THREAD

**Issue by liuqidev** [anjia0532/gcr.io_mirror#22]
As for [Google Datalab for Machine Learning Education](https://github.com/google/eng-edu/blob/master/ml/cc/README.md#with-docker).
>For Mac/Linux:
>docker run -it -p "127.0.0.1:8081:8080" -v "${HOME}:/content" \
 >   gcr.io/cloud-datalab/datalab:local-20170224
>For Windows:
>docker run -it -p "127.0.0.1:8081:8080" -v "\path\to\exercise_directory:/content" gcr.io/cloud-datalab/datalab:local-20170224
>NOTE: If you haven't previously run the above command, Docker will output the message "Unable to find image locally," and then will proceed to download the image.
An image above is necessary,

I input command below on the docker treminal:
```
docker run -it -p "127.0.0.1:8081:8080" -v "E:/ML/google/eng-edu:/content" gcr.io/cloud-datalab/datalab:local-20170
224
```
it shows Error:
```
 Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
```
. So I change  `gcr.io/` to `anjia0532.`, 
```
docker run -it -p "127.0.0.1:8081:8080" -v "E:/ML/google/eng-edu:/content" anjia0532.cloud-datalab.datalab:local-20170
224
```
it shows error below:
```
Error response from daemon: pull access denied for anjia0532/cloud-datalab.datalab, repository does not exist or may require 'docker login'.
```
Is `gcr.io/cloud-datalab` not included in these mirriors?

**Comment by anjia0532** [comment]
only mirror 10 namespace,details from https://github.com/anjia0532/gcr.io_mirror#mirror-10-namespaces-image-from-gcrio

**Comment by anjia0532** [comment]
total of 2000 images,and so large(1.3GB+ and 3G+ every image).

**Comment by anjia0532** [comment]
@liuqidev done! ref https://github.com/anjia0532/gcr.io_mirror/tree/master/cloud-datalab
