### ISSUE TITLE
linkerd controller 18.8.3 似乎同步失败了

### ISSUE THREAD

**Issue by sunng87** [anjia0532/gcr.io_mirror#24]
Github 里可以看到 18.8.3 的 tag，但是 dockerhub 上没有相关镜像

**Comment by anjia0532** [comment]
同步算法bug导致的，我重新同步一下，稍后改一下算法，重新发布。

**Comment by sunng87** [comment]
看到了，thanks!

**Comment by sunng87** [comment]
对了，似乎整个 linkerd 都失败了，能手动整体同步一下吗

**Comment by anjia0532** [comment]
有4个linkerd失败了，都是18.8.3的

**Comment by sunng87** [comment]
现在已经都可以拉到了。多谢！
