### ISSUE TITLE
missing metrics-server-amd64:v0.3.0

### ISSUE THREAD

**Issue by jk-aneirin** [anjia0532/gcr.io_mirror#25]
metrics-server-amd64:v0.3.0  missing

**Comment by anjia0532** [comment]
```bash
$ docker pull anjia0532/google-containers.metrics-server-amd64:v0.3.0
v0.3.0: Pulling from anjia0532/google-containers.metrics-server-amd64
Digest: sha256:6f4a027083d92fd0f28d1aca83364e376e440625ca9a403f1d2d50adaa298d88
Status: Image is up to date for anjia0532/google-containers.metrics-server-amd64:v0.3.0
```

**Comment by anjia0532** [comment]
anjia0532/google-containers.metrics-server-amd64:v0.3.0
eq
gcr.io/google-containers/metrics-server-amd64:v0.3.0
eq
k8s.gcr.io/metrics-server-amd64:v0.3.0

**Comment by jk-aneirin** [comment]
Thank you !

At 2018-09-05 11:32:01, "AnJia" <notifications@github.com> wrote:


anjia0532/google-containers.metrics-server-amd64:v0.3.0
eq
gcr.io/google-containers/metrics-server-amd64:v0.3.0
eq
k8s.gcr.io/metrics-server-amd64:v0.3.0
