### ISSUE TITLE
manifest for anjia0532/istio-release.pilot:latest not found

### ISSUE THREAD

**Issue by katncandix2** [anjia0532/gcr.io_mirror#26]
when i use “docker pull anjia0532/istio-release.pilot”

**Comment by katncandix2** [comment]
不好意思latest 是无法找到的 指定tag 就可以拉了 。。。不过还是想要一个latest 版本比较方便

**Comment by anjia0532** [comment]
这个库，只是一个镜像库，换句话说，gcr.io上是啥样，我原样搬运。所以，不会私自添加latest
