### ISSUE TITLE
manifest for anjia0532/istio-release.pilot:latest not found

### ISSUE THREAD

**Issue by katncandix2** [anjia0532/gcr.io_mirror#27]
使用docker pull anjia0532/istio-release.pilot 尝试获取镜像时
![image](https://user-images.githubusercontent.com/10647224/45436456-6c90e000-b6e5-11e8-8e6c-dacbea796b6d.png)
提示最新版本不存在

**Comment by katncandix2** [comment]
目前是以后面指定版本号解决的、但还是希望能提一个latest thx

**Comment by anjia0532** [comment]
这个库，只是一个镜像库，换句话说，gcr.io上是啥样，我原样搬运。所以，不会私自添加latest

**Comment by anjia0532** [comment]
![snipaste20180913_090047](https://user-images.githubusercontent.com/15098916/45461094-9a9d1100-b733-11e8-8ef1-a2b0f18f64a6.png)
