### ISSUE TITLE
tf_sample镜像

### ISSUE THREAD

**Issue by mashroomxl** [anjia0532/gcr.io_mirror#3]
博主可以添加该镜像不？镜像地址为：gcr.io/tf-on-k8s-dogfood/tf_sample。

**Comment by anjia0532** [comment]
你好，目前只支持 gcr.io/google-containers namespace下的镜像，其余镜像，你可以fork我的代码，稍作改动，实现

**Comment by anjia0532** [comment]
@mashroomxl 已经添加 https://github.com/anjia0532/gcr.io_mirror#total-of-4s-gcriotf-on-k8s-dogfood-images
