### ISSUE TITLE
kube-apiserver:v1.12.1  can't pull

### ISSUE THREAD

**Issue by pzw0612** [anjia0532/gcr.io_mirror#31]
docker pull anjia0532/google-containers.kube-apiserver:v1.12.1 
can't  work

pls  supply   it ,   

thank you .

**Comment by anjia0532** [comment]
[捂脸] 被 gcr.io/kubeflow-images-public/* 的初始化给阻塞住了，目前有1323个需要同步的镜像，目测还得需要个四五天的时间，才能正常同步。你可以打开 https://github.com/anjia0532/gcr.io_mirror/find/master 搜索 `kube-apiserver/v1.12.1` ,来跟踪，如果是`v1.12.1.tmp` 则是待同步，如果是`v1.12.1.tag`则是同步完成

**Comment by pzw0612** [comment]
谢谢

**Comment by anjia0532** [comment]
好了，https://hub.docker.com/r/anjia0532/google-containers.kube-apiserver/tags/
