### ISSUE TITLE
Knative images mirror

### ISSUE THREAD

**Issue by kfchu** [anjia0532/gcr.io_mirror#32]
希望能够提供Knative镜像的mirror：

 docker pull gcr.io/knative-releases/github.com/knative/build/cmd/controller@sha256:5d12da76b8ba36548a97b07866fdc9c13c1cb0e499dfdcca97af731b1ad2c488
Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by anjia0532** [comment]
不支持这种，层级太深了

**Comment by anjia0532** [comment]
只支持 gcr.io/knative-releases/github.com:latest这种的registry_host/namespace/image:tag这种的

**Comment by kfchu** [comment]
@anjia0532 gcr.io/knative-releases/github.com:latest 可以满足需求了，麻烦添加一下，谢谢

**Comment by anjia0532** [comment]
问题是，压根没有gcr.io/knative-releases/github.com:latest啊，能翻墙不？你可以自己上 https://console.cloud.google.com/gcr/images/knative-releases/GLOBAL
 看看

![snipaste20181011_105519](https://user-images.githubusercontent.com/15098916/46777963-30808780-cd44-11e8-9537-11f97deacc3e.png)

![snipaste20181011_105618](https://user-images.githubusercontent.com/15098916/46778006-4d1cbf80-cd44-11e8-8a65-038283fef75a.png)

这种没法通过之前的规则来替换，你可以自己用境外服务器 docker pull && docker tag && docker push 来自己镜像，也可以用https://travis-ci.org 来做
