### ISSUE TITLE
缺少以下镜像

### ISSUE THREAD

**Issue by herryliq** [anjia0532/gcr.io_mirror#34]
gcr.io/cloudsql-docker/gce-proxy:1.11
gcr.io/google-appengine/python

**Comment by anjia0532** [comment]
你可以提pr，在首页有讲

**Comment by herryliq** [comment]
在首页上没看到你说的这个内容呀

**Comment by anjia0532** [comment]
https://github.com/anjia0532/gcr.io_mirror#add-new-namespace

**Comment by herryliq** [comment]
已经添加了pull request。

**Comment by anjia0532** [comment]
python 好了 https://github.com/anjia0532/gcr.io_mirror/tree/master/google-appengine/python
gce-proxy 还没有 https://github.com/anjia0532/gcr.io_mirror/tree/master/cloudsql-docker/gce-proxy
