### ISSUE TITLE
repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by An0nymous0** [anjia0532/gcr.io_mirror#36]
[vagrant@localhost istio-1.0.2]$ **docker pull anjia0532/google_containers.kube-apiserver-amd64:v1.7.3**
Error response from daemon: pull access denied for anjia0532/google_containers.kube-apiserver-amd64, repository does not exist or may require 'docker login'

没用错吧？

**Comment by anjia0532** [comment]
这个镜像是存在的，
```bash
$ docker pull anjia0532/google-containers.kube-apiserver-amd64:v1.7.3
v1.7.3: Pulling from anjia0532/google-containers.kube-apiserver-amd64
daacdb2949be: Pull complete 
aa5f7a791192: Pull complete 
Digest: sha256:ea058d7c19a31a2c9229ad6afab47b4e98c120b6b048afbe41d8b8f64fdf8f50
Status: Downloaded newer image for anjia0532/google-containers.kube-apiserver-amd64:v1.7.3
```
而且也不需要登录，怀疑你是不是改过默认registry？你可以试试`docker pull docker.io/anjia0532/google-containers.kube-apiserver-amd64:v1.7.3`
