### ISSUE TITLE
[QUESTION]希望增加--platform选项，支持拉取对应架构的镜像

### ISSUE THREAD

**Issue by KarlvenK** [anjia0532/gcr.io_mirror#3651]
例如拉取arm架构镜像 
`docker pull image:tag --platform arm64`

**Comment by anjia0532** [comment]
我抽空搞一下

**Comment by anjia0532** [comment]
可以了，issues 格式为  `[PORTER]docker.io/busybox:latest|linux/amd64` 

拉取命令为 `docker pull anjia0532/docker.busybox:latest  --platform linux/amd64`
