### ISSUE TITLE
配置私服请教

### ISSUE THREAD

**Issue by im-jinxinwang** [anjia0532/gcr.io_mirror#3893]
我这边配置好私服后，自动运行会出现这个问题。我不知道那里配置错了，请指教一下，感谢。
![image](https://github.com/anjia0532/gcr.io_mirror/assets/39941928/3d008bc1-3347-4eec-9b8f-c7e29ee909ca)

**Comment by im-jinxinwang** [comment]
[anjia0532@gmail.com](mailto:anjia0532@gmail.com)
![image](https://github.com/anjia0532/gcr.io_mirror/assets/39941928/ccd9dc42-17a7-4e95-8812-73556788021d)

**Comment by anjia0532** [comment]
你自己随便开个issues，在右边创建个 `porter` label，后边通过模板创建会自动带上，就没问题了。
![image](https://github.com/anjia0532/gcr.io_mirror/assets/15098916/f835f840-aaf9-49d3-8012-577d212230b8)

![image](https://github.com/anjia0532/gcr.io_mirror/assets/15098916/55a5c1f5-74fe-47c1-a9cc-4430c26afeaa)
