### ISSUE TITLE
[PORTER]k8s.gcr.io/kube-state-metrics-arm64/kube-state-metrics:v2.4.1

### ISSUE THREAD

**Issue by xuheng44** [anjia0532/gcr.io_mirror#517]

**Comment by xuheng44** [comment]
请问如何同步arm64的kube-state-metrics，我看docker hub上都是amd的，我按照guide尝试一下也失败了。

**Comment by anjia0532** [comment]
@xuheng44 所以你是看不懂错误信息还是咋滴？
![image](https://user-images.githubusercontent.com/15098916/162344654-0bf20f2e-0c61-4925-87a0-98278485698a.png)

**Comment by xuheng44** [comment]
> @xuheng44 所以你是看不懂错误信息还是咋滴？ ![image](https://user-images.githubusercontent.com/15098916/162344654-0bf20f2e-0c61-4925-87a0-98278485698a.png)

不好意思，我用的苹果M1的芯片，所以需要Arm64的，后面加-arm64是我猜测的，我想知道如何同步arm64的image，我直接用anjia的link，下载的还是amd的image, 这个是无法启动的。

**Comment by anjia0532** [comment]
所以你是不会[百度](https://www.baidu.com/s?wd=kube-state-metrics%20arm64)/[bing](https://cn.bing.com/search?q=kube-state-metrics+arm64)/[google](https://www.google.com/search?q=kube-state-metrics+arm64)?

e.g. `kube-state-metrics amd64` 

所有 tags https://k8s.gcr.io/v2/kube-state-metrics/kube-state-metrics/tags/list

**Comment by xuheng44** [comment]
我用google查了，说kube-state-metrics从2.0开始支持multiarch ， 但我不知道在这里配置multiarch.
我这个issue就是用了kube-state-metrics-arm64，但是失败了。

**Comment by anjia0532** [comment]
@xuheng44 你去他家repo里搜一下不就行了？https://github.com/kubernetes/kube-state-metrics/search?q=arm64&type=issues 随便打开个看看

**Comment by xuheng44** [comment]
多谢，已经搞定了
