### ISSUE TITLE
拉取后的 sha256 值与原镜像的 sha256 值不匹配

### ISSUE THREAD

**Issue by xtay573269555** [anjia0532/gcr.io_mirror#600]
拉取后的 sha256 值与原镜像的 sha256 值不匹配。

[599中的构建过程](https://github.com/anjia0532/gcr.io_mirror/runs/6125175792?check_suite_focus=true)

原 sha256 是这个：
Digest: sha256:31f47c1e202b39fadecf822a9b76370bd4baed199a005b3e7d4d1455f4fd3fe2
Status: Downloaded newer image for k8s.gcr.io/ingress-nginx/controller:v1.1.3

中转后的 sha256 变成了这个：
v1.1.3: digest: sha256:dffe4f5b082eadb5d4c9680c80319bf45447609b26330faafa6e4fef5c6a1e59 size: 3463

理论上，这种 pull 后再 push，应该不会改变 sha256 的。请问是中间做了什么变更吗？

**Comment by anjia0532** [comment]
https://github.com/anjia0532/gcr.io_mirror/blob/master/.github/workflows/gcr.io_mirror.yml#L122-L126

**Comment by xtay573269555** [comment]
嗯，我也自己测试了。同一个镜像，自己上传到仓库，sha256也会改变。并不是转换工具的问题。
谢谢！
