### ISSUE TITLE
Hi, better to mirror also gcr.io/kubernetes-helm/* . Thanks a lot! 

### ISSUE THREAD

**Issue by dongdan39** [anjia0532/gcr.io_mirror#9]

**Comment by anjia0532** [comment]
sorry,this is only mirror from gcr.io/google_containers/* , u can fork this repo and do yourself

**Comment by anjia0532** [comment]
@dongdan39 added gcr.io/kubernetes-helm/*  ref https://github.com/anjia0532/gcr.io_mirror#total-of-3s-gcriokubernetes-helm-images
